SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO AS I, (SELECT T.ITEM_ID AS ID
                  FROM ITEM_INFO AS II, ITEM_TREE AS T
                  WHERE II.ITEM_ID=T.PARENT_ITEM_ID and II.RARITY='RARE') AS MIX
WHERE I.ITEM_ID = MIX.ID
ORDER BY ITEM_ID DESC;